# Generated by Django 3.2 on 2021-09-05 15:44

import charity.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', charity.models.UserManager()),
            ],
        ),
    ]
